steps:
- name: "noobzik/uv-gcp-cloud-build"
  id: CI
  entrypoint: /bin/bash
  secretEnv: ['SERVICE_ACCOUNT']
  env:
    - PROJECT_ID=$PROJECT_ID
  args:
    - -c
    - |
      mkdir -p conf/local
      echo "$$SERVICE_ACCOUNT" > conf/local/service_account.json
      if ! gcloud auth activate-service-account --key-file=conf/local/service_account.json; then
        echo "ERROR: gcloud authenfication failed!"
        exit 1
      fi
      gcloud config set project "$PROJECT_ID"

      chmod a+x install.sh
      ./install.sh
      source .venv/bin/activate

      # Facultatif : pour le code Python qui attend la var GOOGLE_APPLICATION_CREDENTIALS
      export GOOGLE_APPLICATION_CREDENTIALS=conf/local/service_account.json

      python -m pytest ./tests/pipelines/data_processing
      python -m pytest ./tests/pipelines/model_training

logs_bucket: gs://bucket_projet_mlops/logs_build_cloud_build
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/cloud-build/versions/1
    env: SERVICE_ACCOUNT
