# Liste des Cloud Builders : https://console.cloud.google.com/gcr/images/cloud-builders/GLOBAL
steps:
- name: "noobzik/uv-gcp-cloud-build"
  id: CI
  entrypoint: /bin/bash
  secretEnv: ['GOOGLE_APPLICATION_CREDENTIALS']
  env:
    - PROJECT_ID=$PROJECT_ID
  args:
  - -c
  - |
    echo "$$GOOGLE_APPLICATION_CREDENTIALS" > GOOGLE_APPLICATION_CREDENTIALS.json
    if ! gcloud auth activate-service-account --key-file=GOOGLE_APPLICATION_CREDENTIALS.json; then
      echo "ERROR: gcloud authenfication failed!"
      exit 1
    fi
    gcloud config set project "$PROJECT_ID"
    chmod a+x install.sh &&
    ./install.sh &&
    source .venv/bin/activate &&
    pytest .

logs_bucket: gs://purchase_predict/logs_build_cloud_build
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/cloud-build/versions/1
    env: GOOGLE_APPLICATION_CREDENTIALS