# Liste des Cloud Builders : https://console.cloud.google.com/gcr/images/cloud-builders/GLOBAL
steps:
- name: "noobzik/uv-gcp-cloud-build"
  id: CI
  entrypoint: /bin/bash
  secretEnv: ['SERVICE_ACCOUNT']
  env:
    - PROJECT_ID=$PROJECT_ID
  args:
  - -c
  - |
    echo "$$SERVICE_ACCOUNT" > service_account.json
    if ! gcloud auth activate-service-account --key-file=service_account.json; then
      echo "ERROR: gcloud authenfication failed!"
      exit 1
    fi
    gcloud config set project "$PROJECT_ID"
    chmod a+x install.sh &&
    ./install.sh &&
    source .venv/bin/activate &&
    export GOOGLE_APPLICATION_CREDENTIALS=service_account.json &&
    export PYTHONPATH=$(pwd)/src &&
    python -m pytest ./tests/pipelines/data_processing &&
    python -m pytest ./tests/pipelines/model_training

logs_bucket: gs://bucket_projet_mlops/logs_build_cloud_build
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/cloudbuild/versions/1
    env: SERVICE_ACCOUNT